### ISSUE TITLE
btTriMeshCollisionShapeFromOSG does not work

### ISSUE THREAD

**Issue by AlbertFX91** [mccdo/osgbullet#36]
Hi,

I am trying to use the btTriMeshCollisionShapeFromOSG in the example demo called collision, but it looks like this type of collisionShape doesn't work. 

The collision shape btConvexTriMeshCollisionShapeFromOSG works but I don't know why with the first one the collisions are not detected.

**Comment by pmartz** [comment]
I recall this is a Bullet issue, not osgBullet. I believe we added the code to osgBullet before we realized the underlying Bullet collision shape was non-functional, but then we never removed the osgBullet code, hoping Bullet would one day properly handle collisions with its own non-convex triangle meshes.
   -Paul

**Comment by AlbertFX91** [comment]
@pmartz thank you so much for your reply! 🥇 

I'll try to compile osgBullet with the new bullet version in order to check if this type of collision works.

I know that this version of osgBullet works with 2.80 but, What will I lose? :) 🤓
